/*
this code and file was mainly to test psrs and qsort codes that i wrote. benchmarking and results were generated by 'benchmark.c'
*/

#include <stdio.h>
#include <stdlib.h>
#include <sys/time.h>
#include "sort.h"

// generate random array with random values
int* generateRandomArray(int sizeofarray) {
    int* arr = (int*) malloc(sizeofarray * sizeof(int));
    for(int i = 0; i < sizeofarray; i++) {
        arr[i] = random(); 
    }
    return arr;
}

// main function
int main(int argc, char** argv) {
    int n = 1000000;  // default array size (if i dont give input via terminal)
    int p = 4;        // default number of threads(if i dont give input via terminal)
    if(argc >= 2) {
        n = atoi(argv[1]);
    }
    if(argc >= 3) {
        p = atoi(argv[2]);
    }
    
    printf("psrs starting ... \n");

    // set threads and array bfr running psrs
    set_num_threads(p);
    srandom(67); 
    int* arr = generateRandomArray(n);
    
    // psrs
    struct timeval start_time, end_time; // (using timeval as time_t was not working will and not too high resolution...)
    gettimeofday(&start_time, NULL);
    psrs(arr, n);
    gettimeofday(&end_time, NULL);
    
    // post psrs
    double elapsed = (end_time.tv_sec - start_time.tv_sec) + 
                     (end_time.tv_usec - start_time.tv_usec) / 1000000.0;
    
    printf("Sorting completed in %.6f seconds\n", elapsed);
    free(arr);
    
    return 0;
}
